name: Reproduction
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        item:
          # Here you can add your fork of Renode
          - repository: 'https://github.com/renode/renode'
            revision: v1.16.1
            name: renode-stable
          - repository: 'https://github.com/renode/renode'
            revision: master
            name: renode-latest
          # - repository: 'https://github.com/your-organization/renode'
          #   revision: your-branch
          #   name: renode-custom
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Configure git and artifacts dir
        run: |
          git config --global user.name "Antmicro"
          git config --global user.email "contact@antmicro.com"
      
      - uses: actions/download-artifact@v4
        with:
          name: build-results
          path: artifacts

      - name: Prepare Python dependencies
        run: pip3 install -r requirements.txt

      - name: Run tests on Renode
        uses: antmicro/renode-test-action@v5
        with:
            renode-repository: ${{ matrix.item.repository }}
            renode-revision: ${{ matrix.item.revision }}
            tests-to-run: 'test.robot'

      - name: Archive Renode simulation results
        uses: actions/upload-artifact@v4
        with:
            name: test-results-${{ matrix.item.name }}
            path: |
                report.html
                log.html
                robot_output.xml

  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Configure git and artifacts dir
        run: |
          git config --global user.name "Antmicro"
          git config --global user.email "contact@antmicro.com"

      - name: Run custom build.sh
        run: ./build.sh

      - name: Archive build results
        uses: actions/upload-artifact@v4
        with:
            name: build-results
            path: |
                artifacts
    
