name: Reproduction
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Configure git and artifacts dir
        run: |
          git config --global user.name "Antmicro"
          git config --global user.email "contact@antmicro.com"

      - name: Run custom build.sh
        run: ./build.sh

      - name: Prepare Python dependencies
        run: pip3 install -r requirements.txt

      - name: Archive build results
        uses: actions/upload-artifact@v4
        with:
            name: build-results
            path: |
                artifacts

      - name: Run tests on latest Renode
        uses: antmicro/renode-test-action@v5
        with:
            renode-repository: 'https://github.com/renode/renode'
            renode-revision: 'master'
            tests-to-run: 'test.robot'

      - name: Archive Renode latest results
        uses: actions/upload-artifact@v4
        with:
            name: test-results-latest
            path: |
                report.html
                log.html
                robot_output.xml

      - name: Run tests on Renode stable release
        uses: antmicro/renode-test-action@v5
        with:
            renode-revision: 'v1.16.0'
            tests-to-run: 'test.robot'

      - name: Archive Renode release results
        uses: actions/upload-artifact@v4
        with:
            name: test-results-stable
            path: |
                report.html
                log.html
                robot_output.xml

